name: Deploy Production Docs
on:
  push:
    branches:
      - main
    paths:
      - 'djtools/**.py'
      - 'docs/**.md'
      - 'mkdocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 
        uses: actions/checkout@main

      - name: Set up Python 3.9
        uses: actions/setup-python@main
        with:
          python-version: 3.9
          cache: 'pip'

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable ".[dev]"

      - name: Deploy docs
        run: |
          mkdocs gh-deploy --force