name: Deploy Development Docs
on:
  push:
    branches:
      - 'releases/**'
    paths:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@main
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development-requirements.txt

      - name: Checkout main repo 
        uses: actions/checkout@v2
        with:
          path: 'main-repo'

      - name: Checkout dev docs repo 
        uses: actions/checkout@v2
        with:
          repository: a-rich/DJ-Tools-dev-docs
          path: 'dev-docs-repo'
          token: ${{ secrets.DJTOOLS_WORKFLOWS }}

      - name: Update and deploy docs
        run: |
          cd dev-docs-repo/
          rm -rf docs 
          cp -r ../main-repo/docs docs
          git add .
          git commit -m $GITHUB_SHA
          git push
          mkdocs gh-deploy
