name: Pylint
on:
  pull_request:
    paths:
      - 'djtools/**.py'
      - 'testing/**.py'
      - '.pylintrc'
      - 'development-requirements.txt'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PYLINT_PASS_SCORE: "10.00"

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Set up Python 3.9
        uses: actions/setup-python@main
        with:
          python-version: 3.9
          cache: 'pip'

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development-requirements.txt

      - name: Run pylint
        run: |
          PYLINT=`pylint $(git ls-files '*.py')`
          PASS=`echo $PYLINT | grep "Your code has been rated at ${{ env.PYLINT_PASS_SCORE}}/10"`
          if [ -z $PASS ]; then
            echo $PYLINT
            exit 1;
          fi
