name: Pytest Coverage
on:
  pull_request:
    paths:
      - 'djtools/**.py'
      - 'tests/**.py'
      - 'conftest.py'
      - 'pyproject.toml'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      COVERAGE_SINGLE: 0
      COVERAGE_TOTAL: 100

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Set up Python 3.9
        uses: actions/setup-python@main
        with:
          python-version: 3.9
          cache: 'pip'

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable ".[dev]"
          pip freeze > requirements.txt

      - name: pytester-cov
        id: pytester-cov
        uses: programmingwithalex/pytester-cov@main
        with:
          pytest-root-dir: 'djtools/'
          pytest-tests-dir: 'tests/'
          requirements-file: 'requirements.txt'
          cov-omit-list: 'djtools/__main__.py'
          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
      
      - name: Coverage total fail - exit
        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
        run: |
          echo "cov total fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
          echo -e "report:\n${{ steps.pytester-cov.outputs.output-table }}"
          exit 1

      - name: Commit pytest coverage table
        uses: peter-evans/commit-comment@main
        with:
          body: ${{ steps.pytester-cov.outputs.output-table }}
