name: Test and Lint
on:
  pull_request:
    paths:
      - 'src/**.py'
      - 'tests/**.py'
      - 'conftest.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    env:
      COVERAGE_SINGLE: 0
      COVERAGE_TOTAL: 100
      PYLINT_PASS_SCORE: "10.00"

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Set up Python 3.9
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable ".[dev]"
          pip freeze > requirements.txt

      - name: Run pylint
        run: |
          PYLINT=`pylint $(git ls-files '*.py')`
          PASS=`echo $PYLINT | grep "Your code has been rated at ${{ env.PYLINT_PASS_SCORE}}/10"`
          if [ -z $PASS ]; then
            echo $PYLINT
            exit 1;
          fi
          rm -rf src

      - name: pytester-cov
        id: pytester-cov
        uses: programmingwithalex/pytester-cov@main
        with:
          pytest-root-dir: 'src'
          pytest-tests-dir: 'tests'
          requirements-file: 'requirements.txt'
          cov-omit-list: 'src/djtools/__main__.py'
          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
      
      - name: Coverage total fail - exit
        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
        run: |
          echo "cov total fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
          echo -e "report:\n${{ steps.pytester-cov.outputs.output-table }}"
          exit 1

      - name: Commit pytest coverage table
        uses: peter-evans/commit-comment@main
        with:
          body: ${{ steps.pytester-cov.outputs.output-table }}
